/* Asynchronous action types */

// USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";
export const RESET_LOGIN_FORM = "RESET_LOGIN_FORM";

export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FULFILLED = "REGISTER_USER_FULFILLED";
export const REGISTER_USER_REJECTED = "REGISTER_USER_REJECTED";
export const RESET_REGISTER_FORM = "RESET_REGISTER_FORM";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const RESET_USER = "RESET_USER";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";
export const FETCH_USERS_CACHED_FULFILLED = "FETCH_USERS_CACHED_FULFILLED";

// ME ACTIONS
export const FETCH_ME = "FETCH_ME";
export const FETCH_ME_FULFILLED = "FETCH_ME_FULFILLED";
export const FETCH_ME_REJECTED = "FETCH_ME_REJECTED";
export const FETCH_ME_CACHED_FULFILLED = "FETCH_ME_CACHED_FULFILLED";

export const FETCH_ME_JAMS = "FETCH_ME_JAMS";
export const FETCH_ME_JAMS_FULFILLED = "FETCH_ME_JAMS_FULFILLED";
export const FETCH_ME_JAMS_REJECTED = "FETCH_ME_JAMS_REJECTED";
export const FETCH_ME_JAMS_CACHED_FULFILLED = "FETCH_ME_JAMS_CACHED_FULFILLED";

export const FETCH_JAMS_BY_USER_CACHE = "FETCH_JAMS_BY_USER_CACHE";
export const FETCH_JAMS_BY_USER_CACHE_FULFILLED =
  "FETCH_JAMS_BY_USER_CACHE_FULFILLED";
export const FETCH_JAMS_BY_USER_CACHE_REJECTED =
  "FETCH_JAMS_BY_USER_CACHE_REJECTED";

export const FETCH_JAMS_BY_USER_ID = "FETCH_JAMS_BY_USER_ID";
export const FETCH_JAMS_BY_USER_ID_FULFILLED =
  "FETCH_JAMS_BY_USER_ID_FULFILLED";
export const FETCH_JAMS_BY_USER_ID_REJECTED = "FETCH_JAMS_BY_USER_ID_REJECTED";

export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_FULFILLED = "FOLLOW_USER_FULFILLED";
export const FOLLOW_USER_REJECTED = "LOGIN_USER_REJECTED";

export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const UNFOLLOW_USER_FULFILLED = "UNFOLLOW_USER_FULFILLED";
export const UNFOLLOW_USER_REJECTED = "UNFOLLOW_USER_REJECTED";

export const SHOW_ME_MODAL = "SHOW_ME_MODAL";
export const CLOSE_ME_MODAL = "CLOSE_ME_MODAL";

export const SHOW_EDIT_ME_MODAL = "SHOW_EDIT_ME_MODAL";
export const CLOSE_EDIT_ME_MODAL = "CLOSE_EDIT_ME_MODAL";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_FULFILLED = "EDIT_PROFILE_FULFILLED";
export const EDIT_PROFILE_REJECTED = "EDIT_PROFILE_REJECTED";

export const RESET_EDIT_PROFILE_FORM = "RESET_EDIT_PROFILE_FORM";

// JAMS ACTIONS
export const FETCH_JAM = "FETCH_JAM";
export const FETCH_JAM_FULFILLED = "FETCH_JAM_FULFILLED";
export const FETCH_JAM_REJECTED = "FETCH_JAM_REJECTED";

export const FETCH_JAMS = "FETCH_JAMS";
export const FETCH_JAMS_FULFILLED = "FETCH_JAMS_FULFILLED";
export const FETCH_JAMS_REJECTED = "FETCH_JAMS_REJECTED";

export const FETCH_JAMS_CACHED_FULFILLED = "FETCH_JAMS_CACHED_FULFILLED";

export const JOIN_JAM = "JOIN_JAM";
export const JOIN_JAM_FULFILLED = "JOIN_JAM_FULFILLED";
export const JOIN_JAM_REJECTED = "JOIN_JAM_REJECTED";

export const CREATE_JAM = "CREATE_JAM";
export const CREATE_JAM_FULFILLED = "CREATE_JAM_FULFILLED";
export const CREATE_JAM_REJECTED = "CREATE_JAM_REJECTED";
export const RESET_CREATE_JAM_FORM = "RESET_CREATE_JAM_FORM";
