/* Asynchronous action types */

// USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

// ME ACTIONS
export const FETCH_ME = "FETCH_ME";
export const FETCH_ME_FULFILLED = "FETCH_ME_FULFILLED";
export const FETCH_ME_REJECTED = "FETCH_ME_REJECTED";

export const FETCH_ME_JAMS = "FETCH_ME_JAMS";
export const FETCH_ME_JAMS_FULFILLED = "FETCH_ME_JAMS_FULFILLED";
export const FETCH_ME_JAMS_REJECTED = "FETCH_ME_JAMS_REJECTED";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_FULFILLED = "FOLLOW_USER_FULFILLED";
export const FOLLOW_USER_REJECTED = "LOGIN_USER_REJECTED";

export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const UNFOLLOW_USER_FULFILLED = "UNFOLLOW_USER_FULFILLED";
export const UNFOLLOW_USER_REJECTED = "UNFOLLOW_USER_REJECTED";

export const SHOW_ME_MODAL = "SHOW_ME_MODAL";
export const CLOSE_ME_MODAL = "CLOSE_ME_MODAL";

// JAMS ACTIONS
export const FETCH_JAM = "FETCH_JAM";
export const FETCH_JAM_FULFILLED = "FETCH_JAM_FULFILLED";
export const FETCH_JAM_REJECTED = "FETCH_JAM_REJECTED";

export const FETCH_JAMS = "FETCH_JAMS";
export const FETCH_JAMS_FULFILLED = "FETCH_JAMS_FULFILLED";
export const FETCH_JAMS_REJECTED = "FETCH_JAMS_REJECTED";

export const JOIN_JAM = "JOIN_JAM";
export const JOIN_JAM_FULFILLED = "JOIN_JAM_FULFILLED";
export const JOIN_JAM_REJECTED = "JOIN_JAM_REJECTED";
